"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Brake_1 = require("./Brake");
var Car_1 = require("./Car");
var Move_1 = require("./Move");
var car = new Car_1.Car();
var accelerate = new Move_1.Move();
var brake = new Brake_1.Brake();
console.log("Car");
console.log(car.start());
car.operation(2, 3);
console.log("\n                -----------------------------------------------------\n                ");
console.log("accelerate");
console.log(accelerate.start());
accelerate.operation(3, 3);
console.log("\n                -----------------------------------------------------\n");
console.log("brake");
console.log(brake.start());
brake.operation(3, 3);
console.log("\n                -----------------------------------------------------\n                ");
