"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Grandfather_1 = require("./Grandfather");
var father_1 = require("./father");
var son_1 = require("./son");
var grandfather = new Grandfather_1.Grandfather();
console.log(grandfather.start());
grandfather.operation(10, 20);
console.log("\n                --------------------------------------");
var father = new father_1.Dad();
console.log(father.start());
console.log(father.say());
father.operation(10, 20);
console.log("\n                --------------------------------------");
var son = new son_1.Son();
console.log(son.start());
console.log(son.say());
son.operation(20, 12);
console.log("\n                --------------------------------------");
